### ISSUE TITLE
Request for maintainership

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/site_map#6]
I noticed that the module was last updated six years ago, and the README mentions that additional maintainers are being sought. I'd like to volunteer as a co-maintainer, as we've started using the module in one of our projects and need to address a few issues. Unfortunately, my offer to submit a PR was declined, which is why I'm reaching out.

**Comment by jenlampton** [comment]
That would be great, as soon as we can get you added to the README I'll grant you access to the repo :)

> Unfortunately, my offer to submit a PR was declined, which is why I'm reaching out.

That's funny, there aren't any [declined PRs for this project](https://github.com/backdrop-contrib/site_map/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aclosed), there was only ever one and I just merged it.  How was the offer declined? 

It not a PR, can you please try again?

**Comment by alanmels** [comment]
Unlike with other projects, I don't have access to create PRs on this one. I can fork though.

**Comment by jenlampton** [comment]
That's really strange. Can you send me a link to the branch on your fork? I'd like to see if I can make a PR from your branch.
